### ISSUE TITLE
has no method 'createPool'

### ISSUE THREAD

**Issue by bjm88** [martinj/node-mysql-promise#4]
this is causing a break, if  I use regular mysql it works, with express-myconnection it breaks using promise wrapper...

has no method 'createPool'
//var mysql = require('mysql'),
var db = require('mysql-promise')(),
    myConnection = require('express-myconnection'), // express-myconnection module
    dbOptions = {
      connectionLimit: 20,
      host: 'localhost',
      user: 'root',
      password: 'password1',
      database: 'caredox_prod_copy2',
      debug: false
    };
  
app.use(myConnection(db, dbOptions, 'pool'));

**Comment by martinj** [comment]
This projects intention is not to extend the mysql module. 
It only returns a set of functions to use mysql with promises.

**Comment by bjm88** [comment]
ok thanks, but I am not asking for extension.  I'm simply stating swapping out regular mysql with the mysql-promise doesn't have same functionality.  I thought it is a wrapper to expose all existing api methods with promise like support....no?

**Comment by martinj** [comment]
It does not expose existing mysql api.
