### ISSUE TITLE
please give example that uses pooling

### ISSUE THREAD

**Issue by ajoslin103** [martinj/node-mysql-promise#65]
I am exceedingly happy with this library, (just want to get that out up front!)

I am using it on a Heroku app and it would seem that my connections are not closing - from reading the index.js it would appear that pooling and releasing connections is possible (or works by default?)

My usage follows your examples.

Would you add an example that uses the pooling and closes connections?

thanks for a great library!

Al;

**Comment by ajoslin103** [comment]
I think maybe the connections were not being released when my app was re-deployed -- I'm trying to figure this out.

I've added code to call .end() to close the pool -- still trying to figure out how things are working up there on Heroku

From what I'm reading in your index.js the example you already have already uses a pool of size 10 -- yes?

```
// when we exit we want to be cleaned up
var nodeCleanup = require('node-cleanup');
nodeCleanup(function (exitCode, signal) {
	console.log('draining db pool');
	db.end();
});
```

**Comment by martinj** [comment]
I've personally never had the need to close the pool. 
When the application quits the connections will close automatically.

Usually for a web app i'm draining active http connections then quit the application which should suffice in most cases 

Looking at your example your are not waiting for the `db.end()` to finish, its an async method.

Anyway you should be able to close the connections in the pool with `.end()` e.g

```

var db = require('mysql-promise')();

db.configure({
    "host": "localhost",
    "user": "foo",
    "password": "bar",
    "database": "db"
});

// some time
db.end().then(() => {
  console.log('pool drained');
});
``` 

`.end()` in this modules is just a simple wrapper for https://github.com/mysqljs/mysql#closing-all-the-connections-in-a-pool

**Comment by ajoslin103** [comment]
I think what happened was that Heroku [free] was giving me 10 connections and then when I connected w/my sql tool that was 11 

Thanks for a really great library, I like it A LOT !!
