### ISSUE TITLE
Not Able to Close Connection in this How should i close connection

### ISSUE THREAD

**Issue by abhishekdubey331** [martinj/node-mysql-promise#66]
Please help immediately ho to close the connection from the connection object.

**Comment by martinj** [comment]
If you are using the pool e.g `db.query()` you can close all connections in the pool with `db.end()`;

If you are using single connections with `db.getConnection()`, the connection received can be closed using to different method `.end()` or `.destroy()`  more info about it is available here https://github.com/mysqljs/mysql#terminating-connections

**Comment by abhishekdubey331** [comment]
Thanks Mr. Martin
