### ISSUE TITLE
Can the options support SSL?

### ISSUE THREAD

**Issue by ajpyoung** [martinj/node-mysql-promise#8]
Hello,

Great promise based mysql solution for node. Just a quick question, can it support SSL? How about unsigned big Int? Apologies if this isn't the correct location to ask this question

example:
```
var db = require('mysql-promise')();
var db_init = {
	host     : 'ipaddresstolocation',
	user     : 'username',
	password : 'password',
	database : 'databasename',
	supportBigNumbers: true,
	ssl:{
		ca : fs.readFileSync( '/location/to/server-ca.pem'),
		key : fs.readFileSync( '/location/to/client-key.pem'),
		cert : fs.readFileSync( '/location/to/client-cert.pem')
	}
};

db.configure(db_init);
```

**Comment by martinj** [comment]
This is just a wrapper for https://github.com/felixge/node-mysql check that lib for what supported.
The function `configure()` just pass along the options to `mysql.createPool()`.
